Update release build and ISO location for custom builds.  (#116)
* Added OS version in Custom Build

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Fixed syntax issue

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Update Release Build and ISO location.

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Updated release build structure.

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Use RHEL node for RHEL custom build.

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Removed OS version from release build location.

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

* Updated release build location in email notification

Signed-off-by: Shailesh Vaidya <shailesh.vaidya@seagate.com>

diff --git a/jenkins/custom-ci/centos-7.8-custom-ci-jenkinsfile b/jenkins/custom-ci/centos-7.8-custom-ci-jenkinsfile
--- a/jenkins/custom-ci/centos-7.8-custom-ci-jenkinsfile
+++ b/jenkins/custom-ci/centos-7.8-custom-ci-jenkinsfile
@@ -12,7 +12,7 @@ pipeline {
 		release_dir="/mnt/bigstorage/releases/cortx"
 		integration_dir="$release_dir/github/integration-custom-ci/release/$os_version"
 		components_dir="$release_dir/components/github/custom-ci/release/$os_version"
-		release_tag="custom-build-$os_version-$BUILD_ID"
+		release_tag="custom-build-$BUILD_ID"
 		passphrase = credentials('rpm-sign-passphrase')
 		thrid_party_dir="/mnt/bigstorage/releases/cortx/third-party-deps/centos/centos-7.8.2003"
 		python_deps="/mnt/bigstorage/releases/cortx/third-party-deps/python-packages"
@@ -136,7 +136,7 @@ pipeline {
 			steps {
 				script { build_stage=env.STAGE_NAME }
 				sh label: 'Installed Dependecies', script: '''
-					yum install -y expect rpm-sign rng-tools
+					yum install -y expect rpm-sign rng-tools genisoimage
 					systemctl start rngd
 					'''
 				}
@@ -164,169 +164,167 @@ pipeline {
 					CUSTOM_COMPONENT_NAME="motr|s3server|hare|cortx-ha|provisioner|csm-agent|csm-web|sspl"
 					fi
 
-				for env in "dev" ;
-				do
-					test -d $integration_dir/$release_tag/ && rm -rf $integration_dir/$release_tag
-					mkdir -p $integration_dir/$release_tag/$env
-					pushd $components_dir/$env
+					for env in "dev" ;
+                    do
+						test -d $integration_dir/$release_tag/cortx_iso/ && rm -rf $integration_dir/$release_tag/cortx_iso/
+						mkdir -p $integration_dir/$release_tag/cortx_iso/
+						pushd $components_dir/$env
 							echo $CUSTOM_COMPONENT_NAME
 							echo $CUSTOM_COMPONENT_NAME | tr "|" "\n"
 							for component in $(echo $CUSTOM_COMPONENT_NAME | tr "|" "\n")
-									do
-									echo -e "Copying RPM's for $component"
-									if ls $component/last_successful/*.rpm 1> /dev/null 2>&1; then
-											cp $component/last_successful/*.rpm $integration_dir/$release_tag/$env
-									else
-											echo "Packages not available for $component. Exiting"
-									exit 1
-									fi
+								do
+								echo -e "Copying RPM's for $component"
+								if ls $component/last_successful/*.rpm 1> /dev/null 2>&1; then
+									cp $component/last_successful/*.rpm $integration_dir/$release_tag/cortx_iso/
+								else
+									echo "Packages not available for $component. Exiting"
+								exit 1							   
+								fi
 							done
-					popd
+						popd
 
 
-					pushd $RPM_COPY_PATH
-					for component in `ls -1 | grep -E -v "$CUSTOM_COMPONENT_NAME" | grep -E -v 'luster|halon|mero|motr|csm'`
-					do
+						pushd $RPM_COPY_PATH
+						for component in `ls -1 | grep -E -v "$CUSTOM_COMPONENT_NAME" | grep -E -v 'luster|halon|mero|motr|csm'`
+						do
 							echo -e "Copying RPM's for $component"
 							if ls $component/last_successful/*.rpm 1> /dev/null 2>&1; then
-									cp $component/last_successful/*.rpm $integration_dir/$release_tag/$env
+								cp $component/last_successful/*.rpm $integration_dir/$release_tag/cortx_iso/
 							else
-									echo "Packages not available for $component. Exiting"
-							exit 1
+								echo "Packages not available for $component. Exiting"
+							exit 1	
 							fi
-					done
-				done
+						done
+                    done
 				'''
 			}
 		}
 
-		stage('RPM Validation') {
+        stage('RPM Validation') {
 			steps {
-				script { build_stage=env.STAGE_NAME }
+                script { build_stage=env.STAGE_NAME }
 				sh label: 'Validate RPMS for Mero Dependency', script:'''
-				for env in "dev" ;
-					do
-					set +x
-					echo "VALIDATING $env RPM'S................"
-					echo "-------------------------------------"
-					pushd $integration_dir/$release_tag/$env
-						if [ "${CSM_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${HARE_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${MOTR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${PRVSNR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${S3_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${SSPL_BRANCH}" == "Cortx-v1.0.0_Beta" ]; then
+                for env in "dev" ;
+                do
+                    set +x
+                    echo "VALIDATING $env RPM'S................"
+                    echo "-------------------------------------"
+                    pushd $integration_dir/$release_tag/cortx_iso/
+					if [ "${CSM_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${HARE_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${MOTR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${PRVSNR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${S3_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${SSPL_BRANCH}" == "Cortx-v1.0.0_Beta" ]; then
 						mero_rpm=$(ls -1 | grep "eos-core" | grep -E -v "eos-core-debuginfo|eos-core-devel|eos-core-tests")
 					else
 						mero_rpm=$(ls -1 | grep "cortx-motr" | grep -E -v "cortx-motr-debuginfo|cortx-motr-devel|cortx-motr-tests")
 					fi
-					mero_rpm_release=`rpm -qp ${mero_rpm} --qf '%{RELEASE}' | tr -d '\040\011\012\015'`
-					mero_rpm_version=`rpm -qp ${mero_rpm} --qf '%{VERSION}' | tr -d '\040\011\012\015'`
-					mero_rpm_release_version="${mero_rpm_version}-${mero_rpm_release}"
-					for component in `ls -1`
-						do
-							if [ "${CSM_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${HARE_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${MOTR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${PRVSNR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${S3_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${SSPL_BRANCH}" == "Cortx-v1.0.0_Beta" ]; then
+                    mero_rpm_release=`rpm -qp ${mero_rpm} --qf '%{RELEASE}' | tr -d '\040\011\012\015'`
+                    mero_rpm_version=`rpm -qp ${mero_rpm} --qf '%{VERSION}' | tr -d '\040\011\012\015'`
+                    mero_rpm_release_version="${mero_rpm_version}-${mero_rpm_release}"
+                    for component in `ls -1`
+                    do
+						if [ "${CSM_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${HARE_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${MOTR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${PRVSNR_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${S3_BRANCH}" == "Cortx-v1.0.0_Beta" ] || [ "${SSPL_BRANCH}" == "Cortx-v1.0.0_Beta" ]; then
 							 mero_dep=`echo $(rpm -qpR ${component} | grep -E "eos-core = |mero =") | cut -d= -f2 | tr -d '\040\011\012\015'`
-						else
+						else	 
 							mero_dep=`echo $(rpm -qpR ${component} | grep -E "cortx-motr = |mero =") | cut -d= -f2 | tr -d '\040\011\012\015'`
 						fi
-						if [ -z "$mero_dep" ]
-						then
-							echo "\033[1;33m $component has no dependency to mero - Validation Success \033[0m "
-						else
-							if [ "$mero_dep" = "$mero_rpm_release_version" ]; then
-								echo "\033[1;32m $component mero version matches with integration mero rpm($mero_rpm_release_version) Good to Go - Validation Success \033[0m "
-							else
-								echo "\033[1;31m $component mero version mismatchs with integration mero rpm($mero_rpm_release_version) - Validation Failed \033[0m"
-								exit 1
-							fi
-						fi
-					done
-				done
-				'''
+                        if [ -z "$mero_dep" ]
+                        then
+                            echo "\033[1;33m $component has no dependency to mero - Validation Success \033[0m "
+                        else
+                            if [ "$mero_dep" = "$mero_rpm_release_version" ]; then
+                                echo "\033[1;32m $component mero version matches with integration mero rpm($mero_rpm_release_version) Good to Go - Validation Success \033[0m "
+                            else
+                                echo "\033[1;31m $component mero version mismatchs with integration mero rpm($mero_rpm_release_version) - Validation Failed \033[0m"
+                                exit 1
+                            fi
+                        fi
+                    done
+                done
+                '''
 			}
 		}
 
 		stage ('Sign rpm') {
 			steps {
-				script { build_stage=env.STAGE_NAME }
-				checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'AuthorInChangelog']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'cortx-admin-github', url: 'https://github.com/Seagate/cortx-re']]])
-
-				sh label: 'Generate Key', script: '''
-				set +x
+                script { build_stage=env.STAGE_NAME }
+                
+			 checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'AuthorInChangelog']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'cortx-admin-github', url: 'https://github.com/Seagate/cortx-re']]])
+                
+                sh label: 'Generate Key', script: '''
+                    set +x
 					pushd scripts/rpm-signing
-					cat gpgoptions >>  ~/.rpmmacros
-					sed -i 's/passphrase/'${passphrase}'/g' genkey-batch
-					gpg --batch --gen-key genkey-batch
-					gpg --export -a 'Seagate'  > RPM-GPG-KEY-Seagate
-					rpm --import RPM-GPG-KEY-Seagate
+                    cat gpgoptions >>  ~/.rpmmacros
+                    sed -i 's/passphrase/'${passphrase}'/g' genkey-batch
+                    gpg --batch --gen-key genkey-batch
+                    gpg --export -a 'Seagate'  > RPM-GPG-KEY-Seagate
+                    rpm --import RPM-GPG-KEY-Seagate
 					popd
 				'''
-				sh label: 'Sign RPM', script: '''
-				set +x
-				pushd scripts/rpm-signing
-					chmod +x rpm-sign.sh
-					cp RPM-GPG-KEY-Seagate $integration_dir/$release_tag/dev
-					for rpm in `ls -1 $integration_dir/$release_tag/dev/*.rpm`
-					do
-						./rpm-sign.sh ${passphrase} $rpm
-					done
-				popd
+                sh label: 'Sign RPM', script: '''
+                    set +x
+					pushd scripts/rpm-signing
+                    chmod +x rpm-sign.sh
+                    cp RPM-GPG-KEY-Seagate $integration_dir/$release_tag/cortx_iso/
+                    
+                    for rpm in `ls -1 $integration_dir/$release_tag/cortx_iso/*.rpm`
+                    do
+                    ./rpm-sign.sh ${passphrase} $rpm
+                    done
+					popd
 
-				'''
-				}
+                '''
+			}
 		}
-
+		
 		stage ('Build MANIFEST') {
 			steps {
-				script { build_stage=env.STAGE_NAME }
+                script { build_stage=env.STAGE_NAME }
 
-				sh label: 'Build MANIFEST', script: """
+                sh label: 'Build MANIFEST', script: """
 					pushd scripts/release_support
-					sh build_release_info.sh $integration_dir/$release_tag/dev
+                    sh build_release_info.sh $integration_dir/$release_tag/cortx_iso/
 					sh build_readme.sh $integration_dir/$release_tag
 					popd
-
-					cp $integration_dir/$release_tag/README.txt .
-					cp $integration_dir/$release_tag/dev/RELEASE.INFO .
-				"""
+					
+                    cp $integration_dir/$release_tag/README.txt .
+                    cp $integration_dir/$release_tag/cortx_iso/RELEASE.INFO .
+                """
 			}
 		}
-
-
+		
 		stage ('Repo Creation') {
 			steps {
-			script { build_stage=env.STAGE_NAME }
-			sh label: 'Repo Creation', script: '''
-				pushd $integration_dir/$release_tag/dev
-				rpm -qi createrepo || yum install -y createrepo
-				createrepo .
-				popd
-			'''
+                script { build_stage=env.STAGE_NAME }
+                sh label: 'Repo Creation', script: '''
+                    pushd $integration_dir/$release_tag/cortx_iso/
+                    rpm -qi createrepo || yum install -y createrepo
+                    createrepo .
+                    popd
+                '''
 			}
 		}
-
+		
 		stage ('Generate ISO Image') {
-			steps {
-			sh label: 'Generate ISO Image',script:'''
-				rpm -q genisoimage || yum install genisoimage -y
-				pushd $release_dir/github/integration-custom-ci/release/iso
-				genisoimage -input-charset iso8859-1 -f -J -joliet-long -r -allow-lowercase -allow-multidot -publisher Seagate -o $release_tag.iso $integration_dir/$release_tag/dev
+		    steps {
+		        sh label: 'Generate ISO Image',script:'''
+		        mkdir $integration_dir/$release_tag/iso && pushd $integration_dir/$release_tag/iso
+					genisoimage -input-charset iso8859-1 -f -J -joliet-long -r -allow-lowercase -allow-multidot -publisher Seagate -o $release_tag.iso $integration_dir/$release_tag/cortx_iso/
 				popd
-			'''
-			}
+		        '''
+		    }
 		}
-
+		
 		stage ('Tag Release') {
 			steps {
-			script { build_stage=env.STAGE_NAME }
-			sh label: 'Tag Release', script: '''
-				pushd $release_dir/github/integration-custom-ci/release
-					test -d $release_dir/github/integration-custom-ci/$release_tag && rm -f $release_tag
-					mkdir $release_tag && pushd $release_tag
-					ln -s $integration_dir/$release_tag/dev cortx_iso
-					ln -s $thrid_party_dir 3rd_party
-					ln -s $python_deps python_deps
-				popd
-				echo "Custom Release Build and ISO is available at,"
-				echo "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/$release_tag"
-				echo "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/iso/$release_tag.iso"
-			'''
+                script { build_stage=env.STAGE_NAME }
+                sh label: 'Tag Release', script: '''
+                    pushd $release_dir/github/integration-custom-ci/release/$os_version/$release_tag
+							ln -s $thrid_party_dir 3rd_party
+							ln -s $python_deps python_deps
+                    popd
+                    echo "Custom Release Build and ISO is available at,"
+					echo "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/$os_version/$release_tag/"
+					echo "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/$os_version/$release_tag/iso/$release_tag.iso"
+					
+                '''
 			}
 		}
 	}
@@ -334,7 +332,7 @@ pipeline {
 	post {
 		always {
 			script {
-				env.release_build_location = "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/${env.release_tag}"
+				env.release_build_location = "http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/release/${env.os_version}/${env.release_tag}"
 				env.release_build = "${env.release_tag}"
 				def recipientProvidersClass = [[$class: 'RequesterRecipientProvider']]
 
